version: "3.8"
services:
  app:
    container_name: spring_backend
    env_file:
      - docker.env
    build: .
    ports:
      - "8080:8080"
    networks:
      - spring_network
  postgres:
    container_name: postgres_db
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: tasks
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring_network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - spring_network
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z-cpuv1
    container_name: minio_s3
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${S3_SECRETKEY}
      MINIO_ROOT_PASSWORD: ${S3_ACCESSKEY}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - spring_network
  prometheus:
    image: prom/prometheus
    container_name: my_prometheus
    ports:
      - "9090:9090" # Стандартный порт Прометея
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml # Прокидываем конфиг
    networks:
      - spring_network
  grafana:
    image: grafana/grafana
    container_name: my_grafana
    ports:
      - "3000:3000" # Графана живет на порту 3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=root # Твой пароль для входа
    volumes:
      - grafana_data:/var/lib/grafana # Чтобы не терять дашборды после перезапуска
    networks:
      - spring_network # ОБЯЗАТЕЛЬНО та же сеть, что у Prometheus
    depends_on:
      - prometheus

volumes:
  postgres_data:
  minio_data:
  grafana_data:

networks:
  spring_network:
    driver: bridge